// <auto-generated />
using System;
using LagerstyringClassLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LagerstyringClassLibrary.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250131124541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LagerstyringClassLibrary.Models.Activity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("activity_type")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("device_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("lifecycle_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("activity_type");

                    b.HasIndex("device_id");

                    b.HasIndex("lifecycle_id");

                    b.HasIndex("user_id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.ActivityType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("activity_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ActivityTypes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            activity_type = "Borrow"
                        },
                        new
                        {
                            id = 2,
                            activity_type = "Return"
                        },
                        new
                        {
                            id = 3,
                            activity_type = "Extend"
                        },
                        new
                        {
                            id = 4,
                            activity_type = "Late"
                        });
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.DeviceOverview", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("available_qty")
                        .HasColumnType("int");

                    b.Property<int>("device_type")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("last_ordered")
                        .HasColumnType("datetime2");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("device_type");

                    b.ToTable("DeviceOverview");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.DeviceType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("type_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.LocationCupboard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Roomid")
                        .HasColumnType("int");

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Roomid");

                    b.ToTable("Cupboards");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.LocationRoom", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("location_cupboard_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.Log", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("log_message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("log_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.SingleDevice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Locationid")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("device_overview_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_archived")
                        .HasColumnType("bit");

                    b.Property<int>("location")
                        .HasColumnType("int");

                    b.Property<string>("qr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Locationid");

                    b.HasIndex("device_overview_id");

                    b.HasIndex("status");

                    b.ToTable("SingleDevices");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.StatusType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("status_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("StatusTypes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            status_type = "Available"
                        },
                        new
                        {
                            id = 2,
                            status_type = "Overdue"
                        },
                        new
                        {
                            id = 3,
                            status_type = "Borrowed"
                        },
                        new
                        {
                            id = 4,
                            status_type = "Unavailable"
                        });
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.Activity", b =>
                {
                    b.HasOne("LagerstyringClassLibrary.Models.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("activity_type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LagerstyringClassLibrary.Models.SingleDevice", "SingleDevice")
                        .WithMany("Activities")
                        .HasForeignKey("device_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LagerstyringClassLibrary.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("SingleDevice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.DeviceOverview", b =>
                {
                    b.HasOne("LagerstyringClassLibrary.Models.DeviceType", "DeviceType")
                        .WithMany("Overviews")
                        .HasForeignKey("device_type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.LocationCupboard", b =>
                {
                    b.HasOne("LagerstyringClassLibrary.Models.LocationRoom", "Room")
                        .WithMany("Cupboards")
                        .HasForeignKey("Roomid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.SingleDevice", b =>
                {
                    b.HasOne("LagerstyringClassLibrary.Models.LocationRoom", "Location")
                        .WithMany("Devices")
                        .HasForeignKey("Locationid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LagerstyringClassLibrary.Models.DeviceOverview", "DeviceOverview")
                        .WithMany("Devices")
                        .HasForeignKey("device_overview_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LagerstyringClassLibrary.Models.StatusType", "Statuses")
                        .WithMany("Devices")
                        .HasForeignKey("status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceOverview");

                    b.Navigation("Location");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.DeviceOverview", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.DeviceType", b =>
                {
                    b.Navigation("Overviews");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.LocationRoom", b =>
                {
                    b.Navigation("Cupboards");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.SingleDevice", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.StatusType", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("LagerstyringClassLibrary.Models.User", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
